### ISSUE TITLE
Why do you need to specify the version number

### ISSUE THREAD

**Issue by echopairs** [jansorg/pycharm-flake8#5]
https://github.com/jansorg/pycharm-flake8/blob/2c9bfa4f21033163dd93e29ec36f31e7c8aa7e89/build.gradle#L24

Why do you need to specify the version number instead of automatically matching the version number of intellij version。If no version number is specified， it report cannot find builtin plugin PythonCore

**Comment by jansorg** [comment]
Because the versions of https://plugins.jetbrains.com/plugin/7322-python-community-edition/versions don't necessarily match the build number of the IDE. You have to define a version because it's not a built-in plugin.
